/** French product copy for the Hermes chat thread. */

export const chatCopy = {
  welcome: "Comment puis-je vous aider ?",
  welcomeMechanic: "Un souci mécanique ? Décrivez-le-moi.",
  composerPlaceholder: "Posez une question, @ pour les fichiers, / pour les commandes",
  newSession: "Nouvelle session",
  scrollToBottom: "Aller en bas",
  copy: "Copier",
  copied: "Réponse copiée",
  refresh: "Régénérer",
  more: "Plus",
  stopGenerating: "Arrêter la génération",
  sendMessage: "Envoyer",
  selectModel: "Choisir un modèle",
  selectEffort: "Choisir l’effort",
  selectPermissions: "Choisir les permissions",
  addContext: "Ajouter du contexte ou changer de mode",
  attachFiles: "Joindre des fichiers",
  planMode: "Mode plan",
  speed: "Vitesse",
  speedStandard: "Standard",
  speedFast: "Rapide",
  webSearch: "Recherche web",
  permissionsHelp:
    "Smart et Manual mettent à jour le profil Hermes. Bypass ne concerne que cette session.",
  noModelsForProvider: "Aucun modèle disponible pour ce fournisseur.",
  effortPreference: "Effort",
  reasoningPreference: "Raisonnement",
  streamingThinking: "Réflexion en cours…",
  streamingWriting: "Rédaction en cours…",
  streamingTools: "Exécution d’outils…",
  streamingWorking: "Traitement en cours…",
  today: "Aujourd’hui",
  yesterday: "Hier",
  exportMarkdown: "Exporter en Markdown",
  edit: "Modifier",
  cancel: "Annuler",
  update: "Mettre à jour",
  previousBranch: "Branche précédente",
  nextBranch: "Branche suivante",
} as const;
